version: "3.9"

services:
  minecraft:
    container_name: "mcserver"
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: unless-stopped
    environment:
      MEMORYSIZE: "1G"
      PAPERMC_FLAGS: ""
      PURPURMC_FLAGS: "-DPurpur.IReallyDontWantSpark=true"
      PUID: ""
      PGID: ""
    volumes:
      - ./minecraft_server:/data:rw
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true

