version: "3.9"

services:
  minecraft:
    container_name: "fabricserver"
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: unless-stopped
    environment:
      MEMORYSIZE: "5G"
      PUID: "1000"
      PGID: "984"
    volumes:
      - ./minecraft_server:/data:rw
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true

